name: Build Android APK (Expo Prebuild)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Expo CLI
        run: npm i -g expo-cli

      - name: Install dependencies
        run: npm ci || npm install

      # Generates native android/ folder from Expo config (no local Android Studio needed)
      - name: Prebuild (Expo → native)
        run: npx expo prebuild --non-interactive

      - name: Build debug APK (no signing setup required)
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
