name: Build Android APK (Expo Prebuild)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      CI: 1
      EXPO_NO_TELEMETRY: 1
      EXPO_NO_PROMPT: 1
      # Safe dummy so build-time reads don't crash:
      EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID: dummy.apps.googleusercontent.com
      # 🚫 Tell expo-modules gradle plugin to skip publishing config in CI
      EXPO_SKIP_PUBLISHING: 1
      ORG_GRADLE_PROJECT_expo_skip_publishing: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (sanity check)
        run: |
          pwd
          ls -la
          echo "---- package.json ----"
          [ -f package.json ] && cat package.json || echo "NO package.json at repo root"

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install expo-cli (optional)
        run: npm i -g expo-cli

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      # Minimal image-free app.json to avoid PNG processing issues
      - name: Force minimal image-free app.json
        shell: bash
        run: |
          [ -f app.json ] && cp app.json app.json.bak || true
          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "Data Wallet E2E",
              "slug": "data-wallet-e2e-google",
              "version": "0.2.0",
              "orientation": "portrait",
              "scheme": "datawallet",
              "updates": { "fallbackToCacheTimeout": 0 },
              "assetBundlePatterns": ["**/*"],
              "ios": { "supportsTablet": true },
              "android": {
                "package": "com.example.datawallete2e"
              },
              "web": { "bundler": "metro", "output": "static" }
            }
          }
          EOF
          echo "---- FINAL app.json ----"
          cat app.json

      - name: Validate app.json
        run: node -e "JSON.parse(require('fs').readFileSync('app.json','utf8')); console.log('app.json OK')"

      - name: Expo doctor (non-fatal)
        run: npx expo-doctor || true

      - name: Prebuild (Expo → native)
        run: npx expo prebuild --platform android

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew

      # Safe defaults + JS engine hint
      - name: Write gradle.properties (safe defaults + hermes)
        run: |
          cat > android/gradle.properties << 'EOF'
          org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
          android.useAndroidX=true
          android.enableJetifier=true
          kotlin.code.style=official
          # Let expo templates know we're using Hermes
          expo.jsEngine=hermes
          # Skip publishing config that breaks in some CI setups
          expo.skipPublishing=true
          EOF
          echo "---- android/gradle.properties ----"
          cat android/gradle.properties

      # Ensure SDK levels are sane for RN 0.74 / AGP 8.x
      - name: Patch compile/target/min SDK (if needed)
        run: |
          sed -i 's/compileSdkVersion *[0-9][0-9]*/compileSdkVersion 34/g' android/build.gradle || true
          sed -i 's/minSdkVersion *[0-9][0-9]*/minSdkVersion 23/g' android/app/build.gradle || true
          sed -i 's/targetSdkVersion *[0-9][0-9]*/targetSdkVersion 34/g' android/app/build.gradle || true

      # ✅ Define hermesEnabled both at the root project and inside :app so any plugin can read it
      - name: Define hermesEnabled in root and app
        run: |
          # In root build.gradle, add an ext block if missing
          if ! grep -q "ext {" android/build.gradle; then
            echo "Adding 'ext { hermesEnabled = true }' to root android/build.gradle"
            sed -i '1iext { hermesEnabled = true }' android/build.gradle
          elif ! grep -q "hermesEnabled" android/build.gradle; then
            echo "Injecting hermesEnabled into existing ext block"
            sed -i '0,/ext {/s//ext { hermesEnabled = true\\n/' android/build.gradle
          fi
          # In app/build.gradle, define a top-level variable too (older scripts read here)
          if ! grep -q "^def hermesEnabled" android/app/build.gradle; then
            echo "Adding 'def hermesEnabled = true' to app/build.gradle"
            sed -i '1idef hermesEnabled = true' android/app/build.gradle
          fi
          echo "---- mentions of hermesEnabled ----"
          grep -n "hermesEnabled" -n android/build.gradle android/app/build.gradle || true

      # 🧯 Patch expo-modules-core plugin to skip publishing if env says so (avoids 'components.release' issue)
      - name: Patch expo-modules-core to skip publishing in CI
        run: |
          FILE=node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle
          if [ -f "$FILE" ]; then
            echo "Patching $FILE to guard publishing with env var"
            # Only add once
            if ! grep -q "EXPO_SKIP_PUBLISHING" "$FILE"; then
              # Wrap the publishing block with an if guard
              sed -i 's/components\.release/ (System.getenv("EXPO_SKIP_PUBLISHING") == "1" ? null : components.release ) /g' "$FILE" || true
              # Additionally, if the plugin uses components.withVariants, guard it:
              sed -i 's/components\.withVariants/components.findByName("release") == null \? components : components.withVariants/g' "$FILE" || true
            fi
            echo "Patched (best-effort)."
          else
            echo "ExpoModulesCorePlugin.gradle not found; continuing."
          fi

      # Build and always capture logs so we can debug if it fails
      - name: Build debug APK (verbose, save logs)
        working-directory: android
        run: |
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace --info --warning-mode all --no-daemon --scan | tee ../gradle-build.log
        continue-on-error: true

      # Show the failure summary inline in Actions UI
      - name: Extract error summary from Gradle log
        if: always()
        run: |
          echo "----- LAST 300 LINES -----"
          tail -n 300 gradle-build.log || true
          echo "----- FAILURE BLOCK -----"
          sed -n '/FAILURE:/,$p' gradle-build.log || true
          echo "----- COMMON ERROR PATTERNS -----"
          grep -nEi "(AAPT|error: |FAILURE:|What went wrong|Caused by:|Duplicate class|No matching variant|manifest|hermesEnabled|components\.release)" gradle-build.log | tail -n 200 || true

      # Upload APK only if it exists and build succeeded
      - name: Upload APK (if present)
        if: success() && hashFiles('android/app/build/outputs/apk/debug/app-debug.apk') != ''
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      # Always upload logs/config for troubleshooting
      - name: Upload debug bundle (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-debug-info
          path: |
            gradle-build.log
            android/build.gradle
            android/app/build.gradle
            android/settings.gradle
            android/gradle.properties
            android/app/src/main/AndroidManifest.xml
            app.json
            package.json
