name: Build Android APK (Expo Prebuild)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      CI: 1
      EXPO_NO_TELEMETRY: 1
      EXPO_NO_PROMPT: 1
      EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID: dummy.apps.googleusercontent.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          ls -la

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install expo-cli (optional)
        run: npm i -g expo-cli

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      # 🔧 Overwrite app.json with a MINIMAL, IMAGE-FREE config to avoid jimp/PNG processing entirely
      - name: Force minimal image-free app.json
        shell: bash
        run: |
          # backup any existing config (just in case)
          [ -f app.json ] && cp app.json app.json.bak || true

          cat > app.json << 'EOF'
          {
            "expo": {
              "name": "Data Wallet E2E",
              "slug": "data-wallet-e2e-google",
              "version": "0.2.0",
              "orientation": "portrait",
              "scheme": "datawallet",
              "updates": { "fallbackToCacheTimeout": 0 },
              "assetBundlePatterns": ["**/*"],
              "ios": { "supportsTablet": true },
              "android": {
                "package": "com.example.datawallete2e"
              },
              "web": { "bundler": "metro", "output": "static" }
            }
          }
          EOF

          echo "---- app.json (final) ----"
          cat app.json
          echo "No icon/splash/adaptiveIcon fields present."

      - name: Validate app.json
        run: node -e "JSON.parse(require('fs').readFileSync('app.json','utf8')); console.log('app.json OK')"

      - name: Expo doctor (non-fatal)
        run: npx expo-doctor || true

      - name: Prebuild (Expo → native)
        run: npx expo prebuild --platform android

      - name: Ensure gradlew executable
        run: chmod +x android/gradlew

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      # Build with verbose logs and keep going so we can upload logs even if it fails
      - name: Build debug APK (verbose, save logs)
        working-directory: android
        run: |
          ./gradlew assembleDebug --stacktrace --info --warning-mode all --no-daemon --scan | tee ../gradle-build.log
        continue-on-error: true
      
      # Extract the last error context so it's easy to read in the Actions UI
      - name: Extract error summary from Gradle log
        if: always()
        run: |
          echo "----- Gradle error summary (last 300 lines with key phrases) -----"
          tail -n 300 gradle-build.log | sed -n '/FAILURE:/,$p' || true
          echo "----- Grep common patterns -----"
          grep -iE "(FAILURE:|What went wrong|Caused by:|A failure occurred|error: |e: |No matching variant|Duplicate class|AAPT|manifest)" gradle-build.log | tail -n 200 || true
      
      # Upload full logs and key files so we can diagnose precisely
      - name: Upload build logs and gradle files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-debug-info
          path: |
            gradle-build.log
            android/build.gradle
            android/app/build.gradle
            android/settings.gradle
            android/gradle.properties
            android/app/src/main/AndroidManifest.xml
            app.json
            package.json

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
